#!/usr/bin/env python3
"""Print a synthetic WebP regression header using Pillow/libwebp.

Run from the repository root:
uv run --with pillow python tests/vision-fixtures/generate_webp.py > tests/vision-fixtures/webp.h

Encoder versions may change the compressed bytes; rerun the decoder and server
tests after regeneration. This helper uses no client harness or user data.
"""

import base64
import io
import json

from PIL import Image


def main():
    output = io.BytesIO()
    Image.new("RGBA", (8, 8), (64, 128, 192, 128)).save(
        output, format="WEBP", quality=80, method=4)
    encoded = output.getvalue()
    base64_image = base64.b64encode(encoded).decode("ascii")
    request = {
        "model": "ds4-fixture",
        "messages": [{"role": "user", "content": [
            {"type": "text", "text": "Describe this synthetic square."},
            {"type": "image_url", "image_url": {
                "url": "data:image/webp;base64," + base64_image}},
        ]}],
        "stream": True,
        "stream_options": {"include_usage": True},
        "store": False,
        "max_tokens": 32,
    }
    request_json = json.dumps(request, separators=(",", ":"))
    print("/* Generated by tests/vision-fixtures/generate_webp.py (Pillow/libwebp).")
    print(" * Synthetic 8x8 RGBA square encoded as lossy WebP; no user data. */")
    print("#ifndef DS4_TEST_WEBP_H")
    print("#define DS4_TEST_WEBP_H")
    print("#define DS4_TEST_WEBP_REQUEST " + json.dumps(request_json))
    print("#define DS4_TEST_WEBP_BASE64 " + json.dumps(base64_image))
    print("static const unsigned char ds4_test_webp[] = {")
    for offset in range(0, len(encoded), 12):
        print("    " + ", ".join("0x%02x" % b for b in encoded[offset:offset + 12]) + ",")
    print("};")
    print("#endif")


if __name__ == "__main__":
    main()
